# Generated by Django 5.2.4 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='country',
            field=models.CharField(default='citizen', max_length=50),
        ),
    ]
