# Generated by Django 5.2.4 on 2025-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicalprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='doctor_access_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='country',
            field=models.CharField(default='Kenya', max_length=50),
        ),
    ]
