# Generated by Django 5.2.4 on 2025-07-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_medicalprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('doctor_access_count', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='medical.medicalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('emergency', 'Emergency'), ('doctor', 'Doctor')], default='public', max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='medical.medicalprofile')),
            ],
        ),
    ]
