# Generated by Django 5.2.4 on 2025-08-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_clinic_patient_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('public_view', 'Public Profile Viewed'), ('doctor_view', 'Doctor Full View'), ('download_html', 'Doctor Download HTML'), ('download_pdf', 'Doctor Download PDF')], max_length=20)),
                ('viewer_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='medical.medicalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
