# Generated by Django 5.2.4 on 2025-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_medicalprofile_owner_email_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='health_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='event_type',
            field=models.CharField(choices=[('public_view', 'Public Profile Viewed'), ('doctor_view', 'Doctor Full View'), ('doctor_health_view', 'Doctor Health Monitoring View'), ('download_html', 'Doctor Download HTML'), ('download_pdf', 'Doctor Download PDF')], max_length=20),
        ),
    ]
