# Generated by Django 5.2 on 2025-08-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_profileanalytics_qrscanlog'),
        ('medical', '0007_medicalprofile_health_data_and_more'),
    ]

    operations = [
    ]
