# Generated by Django 5.2 on 2025-10-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_merge_20250819_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrscanlog',
            options={'ordering': ['-scanned_at']},
        ),
    ]
